### ISSUE TITLE
Gérer les fees pour la vente

### ISSUE THREAD

**Issue by AlexVcht** [Alex1664/pumpy-bot#1]
Gérer le calcul des fees pour la quantité à vendre.

**Comment by erwanlbp** [comment]
Je crois que c'est bon
Les fees sont récupérées sur l'odre après qu'il soit passé (je crois) du coup on a pas à s'en faire
Et pour la vente je re-récupère le solde et le prix et tout donc on s'en fout aussi
A vérifier
